name: smart_response_builder
description: "A smart widget for handling API responses, offline states, and pagination in Flutter."
version: 1.0.0
homepage: https://github.com/mirzamahmud/smart_response_builder
repository: https://github.com/mirzamahmud/smart_response_builder
issue_tracker: https://github.com/mirzamahmud/smart_response_builder/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
